apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../imports/application-a/deploy
  - ../../imports/application-b/deploy
  - ../../imports/frontend/deploy
  - ingress.yaml
components:
  - ../../imports/application-a/deploy/components/postgres
